[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ezbotball"
authors = [{name = "EZBotball", email = "jake.ross.215@gmail.com"}]
dynamic = ["version", "description"]
